name: pre-commit
on:
  pull_request:
  push:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      # Inline pre-commit/action@v3.0.1 which is no longer maintained
      - name: "pre-commit/action: pip install pre-commit"
        run: |
          python -m pip install pre-commit
          python -m pip freeze --local

      - name: "pre-commit/action: cache"
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key:
            pre-commit-3|${{ env.pythonLocation }}|${{
            hashFiles('.pre-commit-config.yaml') }}

      - name: "pre-commit/action: pre-commit run"
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files
